CREATE TABLE Director (
    IdDirector VARCHAR2(9),
    Nome VARCHAR(20) NOT NULL,
    Apelido1 VARCHAR(20) NOT NULL,
    Apelido2 VARCHAR(20),
    Nacionalidad VARCHAR(20),
    DataNacemento DATE,
	CONSTRAINT pk_director PRIMARY KEY (IdDirector)
);

CREATE TABLE Pelicula (
    IdPelicula VARCHAR2(9),
    Duracion NUMBER(5) NOT NULL,
    Xenero VARCHAR2(20) NOT NULL,
    FechaEstreno DATE,
    Nacionalidad VARCHAR2(20) NOT NULL,
    Titulo VARCHAR2(40) NOT NULL,
    Productora VARCHAR2(20) NOT NULL,
    IdDirector VARCHAR2(9) NOT NULL,
	CONSTRAINT pk_pelicula PRIMARY KEY (IdPelicula),
    CONSTRAINT uk_Titulo_Productora UNIQUE (Titulo, Productora),
    CONSTRAINT fk_IdDirector FOREIGN KEY (IdDirector) REFERENCES Director(IdDirector) ON DELETE CASCADE,
	CONSTRAINT valid_duracion CHECK (Duracion >= 0)
);

CREATE TABLE Actores(
	IDACTOR		    VARCHAR(9) NOT NULL,
	NOME		    VARCHAR(20) NOT NULL,
	APEL1    	    VARCHAR(20) NOT NULL,
	APEL2   	    VARCHAR(20),
	NACION   	    VARCHAR(20),
	DATANAC  	    DATE,
	CIUDADRES       VARCHAR(20),
	ANOINIPROF	    NUMBER(4),
	ANORETPROF	    NUMBER(4),
	CONSTRAINT pk_actor PRIMARY KEY (IDACTOR),
	CONSTRAINT valid_anos CHECK (ANOINIPROF <= ANORETPROF)
);

CREATE TABLE PARTICIPA (
    IdPelicula VARCHAR2(9) NOT NULL,
    IdActor VARCHAR2(9) NOT NULL,
    Tipo VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_participa PRIMARY KEY (IdPelicula, IdActor),
    CONSTRAINT fk_IdPelicula FOREIGN KEY (IdPelicula) REFERENCES Pelicula(IdPelicula) ON DELETE CASCADE,
    CONSTRAINT fk_IdActor FOREIGN KEY (IdActor) REFERENCES Actores(IdActor) ON DELETE CASCADE,
	CONSTRAINT valid_tipo CHECK (Tipo IN ('Protagonista','Secundario','Antagonista','Villano','Anti-Héroe','Héroe','De Reparto','Extra'))
);

CREATE TABLE Socios(
	DNI	   VARCHAR(9)   NOT NULL,
	NOME	   VARCHAR(20)  NOT NULL,
	TELF   NUMBER(10,0) NOT NULL,    
	DIR  VARCHAR(150),
	CONSTRAINT pk_soc PRIMARY KEY (DNI),
	CONSTRAINT valid_dni CHECK (LENGTH(DNI)=9)	
); 

CREATE TABLE Exemplares(
	NEXEMPLAR	  VARCHAR(4) NOT NULL,
	ESTADO		  VARCHAR(15),
	IDPELICULA	  VARCHAR(9) NOT NULL,
	CONSTRAINT pk_ex PRIMARY KEY (IDPELICULA, NEXEMPLAR),
	CONSTRAINT valid_estado CHECK (ESTADO IN ('OPTIMO','BUENO','MALO','DEPLORABLE'))
);
	
CREATE TABLE Alquiler(
	NEXEMPLAR	  VARCHAR(4) NOT NULL,
	IDPELICULA	  VARCHAR(9) NOT NULL,
	FECHADQUISICION   DATE NOT NULL,
	FECHADEVOLUCION   DATE NOT NULL,
	DNI		  VARCHAR(9) NOT NULL,
	CONSTRAINT pk_alq PRIMARY KEY (IDPELICULA, NEXEMPLAR,FECHADQUISICION),
	CONSTRAINT fk_idpel_nex FOREIGN KEY (IDPELICULA,NEXEMPLAR) REFERENCES Exemplares(IDPELICULA,NEXEMPLAR) ON DELETE CASCADE,
	CONSTRAINT fk_dni FOREIGN KEY (DNI) REFERENCES Socios(DNI),
	CONSTRAINT valid_fechas CHECK (FECHADQUISICION <= FECHADEVOLUCION)
);





